{
  imports = [
    ../profiles/common.nix
    ../profiles/desktop.nix
    ./audio.nix
    ./bluetooth.nix
    ./devtools.nix
    ./docker.nix
    ./env.nix
    ./gsettings.nix
    ./hasp.nix
    ./home-manager.nix
    ./ideco.nix
    ./kernel.nix
    ./linux-app.nix
    ./locale.nix
    ./mime.nix
    ./net.nix
    ./nh.nix
    ./niri.nix
    ./nix.nix
    ./obs.nix
    ./sops.nix
    ./ssh.nix
    ./stylix.nix
    ./timezone.nix
    ./udev.nix
    ./user.nix
    ./xdg.nix
    ./zapret.nix
    ./zram.nix
  ];
}
