{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./env.nix
    ./home-manager.nix
    ./locale.nix
    ./hyprland.nix
    ./kernel.nix
    ./mime.nix
    ./net.nix
    ./nh.nix
    ./nix.nix
    ./obs.nix
    ./ssh.nix
    ./timezone.nix
    ./user.nix
    ./zapret.nix
    #./zerotierone.nix
    ./zram.nix
  ];
}
